export const ACTION_TYPE = {
  SEND_DATA: "SEND_DATA",
  SET_DATA: "SET_DATA",
  SET_USER: "SET_USER",
  SET_WISHLIST: "SET_WHISHLIST",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM",
  CLONE_ALL_ITEM: "CLONE_ALL_ITEM",
  SEARCH_DATA: "SEARCH_DATA",
};
